/*!
 * \file AnimationType.h
 * \brief enum for each animation type
 * \author Chupee
 * \date 22/02/2014
 */
#ifndef GRAPHICS_ANIMATION_TYPE_H
#define GRAPHICS_ANIMATION_TYPE_H

namespace graphics {
typedef enum {
	NO_ANIMATION,
	HERO_IDLE,
	HERO_START_IDLE,
	HERO_WALK,
	HERO_STOP_WALK,
	HERO_START_JUMP,
	HERO_DURING_JUMP,
	HERO_JUMP,
	HERO_FALL,
	HERO_START_BOUNCE,
	HERO_BOUNCE,
	HERO_STOP_BOUNCE,
	HERO_START_CRAWL,
	HERO_CRAWL,
	HERO_STOP_CRAWL,
	HERO_IDLE_CRAWL,
	HERO_FLY,
	HERO_HIT,
	HERO_INTERACT,
	HERO_COUGH,
	HERO_PULL_SWITCH,
	HERO_DIE,
	HERO_WIN,
	HERO_SPAWN,
	BLUE_FIREFLY,
	RED_FIREFLY,
	GREEN_FIREFLY,
} AnimationType;

}  // namespace core
#endif